#' Localized "chrome" strings for the rendered documents
#'
#' The chrome of a rendered review document -- column headers (No,
#' Variable, Type, Mandatory, Filter), row labels (Question,
#' Subquestion, Help, Value), navigation titles (Table of contents,
#' Variable index, Welcome text, End text), MOSAiCH-style type labels
#' (Single choice, Multiple choice, Text, Number, ...), Value
#' descriptors for implicit codings (Y = selected, Numeric input, ...),
#' and audit section labels -- is independent from the survey's
#' content languages. This function returns the full set of chrome
#' strings for a given user-facing language so the renderer can swap
#' them without touching the survey content.
#'
#' Supported languages: `"en"`, `"fr"`, `"de"`, `"es"`, `"it"`.
#' Unknown languages fall back to English with no warning -- the
#' caller is expected to validate the value upstream via
#' [lss_resolve_chrome_lang()].
#'
#' Translation notes:
#' - English is the source language.
#' - French and German are reviewed by the package author.
#' - Spanish and Italian are best-effort and should be reviewed by a
#'   native speaker before publishing an official document.
#'
#' @param lang Length-one character: `"en"`, `"fr"`, `"de"`, `"es"`,
#'   or `"it"`.
#' @return A named list of strings.
#' @keywords internal
#' @noRd
lss_chrome_strings <- function(lang = "en") {
  base <- list(
    # ---- Cover page ----
    cover_subtitle_review = "Questionnaire",
    cover_subtitle_audit  = "Questionnaire audit report",
    cover_source_file     = "Source file",
    cover_survey_id       = "Survey ID",
    cover_languages       = "Languages",
    cover_groups          = "Groups",
    cover_questions       = "Questions",
    cover_subquestions    = "Subquestions",
    cover_answer_options  = "Answer options",
    cover_last_modified   = "LimeSurvey last save",
    cover_generated       = "Generated",
    # ---- Optional cover metadata: privacy / tracking settings ----
    cover_anonymized        = "Anonymized",
    cover_save_partial      = "Save partial",
    cover_timestamp         = "Timestamp",
    cover_ip_recorded       = "IP recorded",
    cover_referrer_recorded = "Referrer recorded",
    # ---- Optional cover metadata: admin settings ----
    cover_active            = "Active",
    cover_alias             = "Alias",
    cover_end_url           = "End URL",
    cover_end_url_description = "End URL description",
    # ---- Survey description heading (text element) ----
    description_title       = "Description",
    # ---- Navigation ----
    toc_title             = "Table of contents",
    welcome_text_title    = "Welcome text",
    end_text_title        = "End text",
    variable_index_title  = "Variable index",
    consent_title         = "Data protection and consent",
    quotas_title          = "Quotas",
    quota_limit           = "Limit",
    quota_when_full       = "When full",
    quota_active          = "active",
    quota_inactive        = "inactive",
    quota_condition       = "Condition",
    quota_message         = "Message when full",
    quota_action_terminate = "terminate survey",
    quota_action_confirm  = "let respondent change answer",
    # ---- Meta table headers ----
    meta_no               = "No",
    meta_variable         = "Variable",
    meta_type             = "Type",
    meta_mandatory        = "Mandatory",
    meta_mandatory_short  = "Mand.",
    meta_filter           = "Filter",
    # ---- Item table row labels ----
    item_language         = "Language",
    item_question         = "Question",
    item_subquestion      = "Subquestion",
    item_help             = "Help",
    item_value            = "Value",
    item_options          = "Options",
    item_value_scale_fmt  = "Value (scale %d)",
    item_scale            = "Scale",
    item_order            = "Order",
    item_column           = "Column",
    item_positions        = "Positions",
    item_rank_fmt         = "Rank %d",
    item_comment          = "Comment",
    item_exclusive        = "Exclusive",
    # ---- Table row labels ----
    item_group            = "Group",
    item_field            = "Field",
    # ---- Mandatory values ----
    # Sentence case to match the row label style used everywhere else
    # in the document ("Question", "Value", "Help", ...). The previous
    # lowercase form clashed with that convention.
    mandatory_yes         = "Yes",
    mandatory_no          = "No",
    mandatory_soft        = "Soft",
    # ---- Filter values ----
    filter_all            = "All",
    filter_and            = "AND",
    filter_or             = "OR",
    filter_answered       = "is answered",
    filter_empty          = "is empty",
    filter_in             = "in",
    filter_matches        = "matches",
    # ---- Type labels (MOSAiCH-style) ----
    type_single_choice              = "Single choice",
    type_single_choice_with_comment = "Single choice with comment",
    type_multiple_choice            = "Multiple choice",
    type_multiple_choice_with_comment = "Multiple choice with comment",
    type_text             = "Text",
    type_text_short       = "Text (short)",
    type_text_long        = "Text (long)",
    type_text_other       = "Text (other)",
    type_number           = "Number",
    type_date             = "Date",
    type_ranking          = "Ranking",
    type_file_upload      = "File upload",
    type_computed         = "Computed",
    type_display          = "Display",
    # ---- Value implicit descriptors ----
    value_multi_y_blank               = "Y = selected, blank = not selected",
    value_multi_y_blank_with_comment  = "Y = selected, blank = not selected (plus a `<subq>comment` text variable)",
    value_yes_no                      = "Y = Yes, N = No",
    value_gender                      = "M = Male, F = Female",
    value_gender_male                 = "Male",
    value_gender_female               = "Female",
    value_5point                      = "1, 2, 3, 4, 5 (1 = lowest, 5 = highest)",
    value_numeric_input               = "Numeric input",
    value_array_yes                   = "Yes",
    value_array_uncertain             = "Uncertain",
    value_array_no                    = "No",
    value_array_increase              = "Increase",
    value_array_same                  = "Same",
    value_array_decrease              = "Decrease",
    value_order_random                = "Labels shown in random order",
    value_order_alphabetical          = "Labels shown in alphabetical order",
    value_npoint_fmt                  = "%d-point scale (1 to %d)",
    value_free_text_short             = "Free text (single line)",
    value_free_text                   = "Free text (multi-line)",
    value_date_input                  = "Date input",
    value_computed                    = "Computed expression (server-side)",
    value_ranking                     = "Ranking (positions assigned to subquestions)",
    value_file_upload                 = "File upload",
    # ---- Exclusive row template ----
    exclusive_text_fmt    = "When checked, clears all other selections of %s",
    # ---- Audit section ----
    audit_findings_title  = "Audit findings",
    audit_no_anomalies    = "No anomalies detected.",
    audit_summary_fmt     = "%d finding(s): %d error(s), %d warning(s), %d note(s).",
    audit_col_severity    = "Severity",
    audit_col_check       = "Check",
    audit_col_location    = "Location",
    audit_col_language    = "Language",
    audit_col_message     = "Message",
    audit_severity_error  = "error",
    audit_severity_warning = "warning",
    audit_severity_note   = "note",
    # ---- ORCID prefix in author block ----
    orcid_label           = "ORCID"
  )

  fr <- list(
    cover_subtitle_review = "Questionnaire",
    cover_subtitle_audit  = "Rapport d'audit du questionnaire",
    cover_source_file     = "Fichier source",
    cover_survey_id       = "Identifiant de l'enqu\u00EAte",
    cover_languages       = "Langues",
    cover_groups          = "Groupes",
    cover_questions       = "Questions",
    cover_subquestions    = "Sous-questions",
    cover_answer_options  = "Modalit\u00E9s de r\u00E9ponse",
    cover_last_modified   = "Derni\u00E8re sauvegarde LimeSurvey",
    cover_generated       = "G\u00E9n\u00E9r\u00E9",
    cover_anonymized        = "Anonymis\u00E9",
    cover_save_partial      = "Sauvegarde partielle",
    cover_timestamp         = "Horodatage",
    cover_ip_recorded       = "IP enregistr\u00E9e",
    cover_referrer_recorded = "Referrer enregistr\u00E9",
    cover_active            = "Actif",
    cover_alias             = "Alias",
    cover_end_url           = "URL de fin",
    cover_end_url_description = "Description de l'URL de fin",
    description_title       = "Description",
    toc_title             = "Table des mati\u00E8res",
    welcome_text_title    = "Texte d'accueil",
    end_text_title        = "Texte de fin",
    variable_index_title  = "Index des variables",
    consent_title         = "Protection des donn\u00e9es et consentement",
    quotas_title          = "Quotas",
    quota_limit           = "Limite",
    quota_when_full       = "Quand atteint",
    quota_active          = "actif",
    quota_inactive        = "inactif",
    quota_condition       = "Condition",
    quota_message         = "Message quand atteint",
    quota_action_terminate = "terminer le questionnaire",
    quota_action_confirm  = "laisser le r\u00E9pondant modifier",
    meta_no               = "N\u00B0",
    meta_variable         = "Variable",
    meta_type             = "Type",
    meta_mandatory        = "Obligatoire",
    meta_mandatory_short  = "Oblig.",
    meta_filter           = "Filtre",
    item_language         = "Langue",
    item_question         = "Question",
    item_subquestion      = "Sous-question",
    item_help             = "Aide",
    item_value            = "Valeur",
    item_options          = "Options",
    item_value_scale_fmt  = "Valeur (\u00E9chelle %d)",
    item_scale            = "\u00C9chelle",
    item_order            = "Ordre",
    item_column           = "Colonne",
    item_positions        = "Positions",
    item_rank_fmt         = "Rang %d",
    item_comment          = "Commentaire",
    item_exclusive        = "Exclusif",
    item_group            = "Groupe",
    item_field            = "Champ",
    mandatory_yes         = "Oui",
    mandatory_no          = "Non",
    # "Souple" rather than "Doux": LimeSurvey "soft mandatory" is the
    # softened-requirement mode (the form warns but still accepts a
    # submission), not "gentle/sweet".
    mandatory_soft        = "Souple",
    filter_all            = "Toutes",
    filter_and            = "ET",
    filter_or             = "OU",
    filter_answered       = "est renseign\u00E9",
    filter_empty          = "est vide",
    filter_in             = "dans",
    filter_matches        = "correspond \u00E0",
    type_single_choice              = "Choix unique",
    type_single_choice_with_comment = "Choix unique avec commentaire",
    type_multiple_choice            = "Choix multiple",
    type_multiple_choice_with_comment = "Choix multiple avec commentaire",
    type_text             = "Texte",
    type_text_short       = "Texte (court)",
    type_text_long        = "Texte (long)",
    type_text_other       = "Texte (autre)",
    type_number           = "Nombre",
    type_date             = "Date",
    type_ranking          = "Classement",
    type_file_upload      = "T\u00E9l\u00E9versement de fichier",
    type_computed         = "Calcul",
    type_display          = "Affichage",
    value_multi_y_blank               = "Y = s\u00E9lectionn\u00E9, vide = non s\u00E9lectionn\u00E9",
    value_multi_y_blank_with_comment  = "Y = s\u00E9lectionn\u00E9, vide = non s\u00E9lectionn\u00E9 (plus une variable texte `<subq>comment`)",
    value_yes_no                      = "Y = Oui, N = Non",
    value_gender                      = "M = Homme, F = Femme",
    value_gender_male                 = "Homme",
    value_gender_female               = "Femme",
    value_5point                      = "1, 2, 3, 4, 5 (1 = plus bas, 5 = plus haut)",
    value_numeric_input               = "Saisie num\u00E9rique",
    value_array_yes                   = "Oui",
    value_array_uncertain             = "Incertain",
    value_array_no                    = "Non",
    value_array_increase              = "Augmenter",
    value_array_same                  = "Sans changement",
    value_array_decrease              = "Diminuer",
    value_order_random                = "Libell\u00e9s pr\u00e9sent\u00e9s dans un ordre al\u00e9atoire",
    value_order_alphabetical          = "Libell\u00e9s pr\u00e9sent\u00e9s par ordre alphab\u00e9tique",
    value_npoint_fmt                  = "\u00C9chelle \u00E0 %d points (1 \u00E0 %d)",
    value_free_text_short             = "Texte libre (une ligne)",
    value_free_text                   = "Texte libre (multi-ligne)",
    value_date_input                  = "Saisie de date",
    value_computed                    = "Expression calcul\u00E9e (c\u00F4t\u00E9 serveur)",
    value_ranking                     = "Classement (positions attribu\u00E9es aux sous-questions)",
    value_file_upload                 = "T\u00E9l\u00E9versement de fichier",
    exclusive_text_fmt    = "Si coch\u00E9, efface toutes les autres s\u00E9lections de %s",
    audit_findings_title  = "Constats d'audit",
    audit_no_anomalies    = "Aucune anomalie d\u00E9tect\u00E9e.",
    audit_summary_fmt     = "%d constat(s) : %d erreur(s), %d avertissement(s), %d note(s).",
    audit_col_severity    = "Gravit\u00E9",
    audit_col_check       = "Contr\u00F4le",
    audit_col_location    = "Localisation",
    audit_col_language    = "Langue",
    audit_col_message     = "Message",
    audit_severity_error  = "erreur",
    audit_severity_warning = "avertissement",
    audit_severity_note   = "note",
    orcid_label           = "ORCID"
  )

  de <- list(
    cover_subtitle_review = "Fragebogen",
    cover_subtitle_audit  = "Audit-Bericht zum Fragebogen",
    cover_source_file     = "Quelldatei",
    cover_survey_id       = "Umfrage-ID",
    cover_languages       = "Sprachen",
    cover_groups          = "Gruppen",
    cover_questions       = "Fragen",
    cover_subquestions    = "Teilfragen",
    cover_answer_options  = "Antwortoptionen",
    cover_last_modified   = "Letzte LimeSurvey-Speicherung",
    cover_generated       = "Erstellt",
    cover_anonymized        = "Anonymisiert",
    cover_save_partial      = "Teilweise speichern",
    cover_timestamp         = "Zeitstempel",
    cover_ip_recorded       = "IP gespeichert",
    cover_referrer_recorded = "Referrer gespeichert",
    cover_active            = "Aktiv",
    cover_alias             = "Alias",
    cover_end_url           = "Abschluss-URL",
    cover_end_url_description = "Beschreibung der Abschluss-URL",
    description_title       = "Beschreibung",
    toc_title             = "Inhaltsverzeichnis",
    welcome_text_title    = "Begr\u00FC\u00DFungstext",
    end_text_title        = "Abschlusstext",
    variable_index_title  = "Variablenverzeichnis",
    consent_title         = "Datenschutz und Einwilligung",
    quotas_title          = "Quoten",
    quota_limit           = "Limit",
    quota_when_full       = "Wenn voll",
    quota_active          = "aktiv",
    quota_inactive        = "inaktiv",
    quota_condition       = "Bedingung",
    quota_message         = "Meldung bei Erreichen",
    quota_action_terminate = "Umfrage beenden",
    quota_action_confirm  = "Antwort \u00e4ndern lassen",
    meta_no               = "Nr.",
    meta_variable         = "Variable",
    meta_type             = "Typ",
    meta_mandatory        = "Pflichtfeld",
    meta_mandatory_short  = "Pflicht",
    meta_filter           = "Filter",
    item_language         = "Sprache",
    item_question         = "Frage",
    item_subquestion      = "Teilfrage",
    item_help             = "Hilfe",
    item_value            = "Wert",
    item_options          = "Optionen",
    item_value_scale_fmt  = "Wert (Skala %d)",
    item_scale            = "Skala",
    item_order            = "Reihenfolge",
    item_column           = "Spalte",
    item_positions        = "Positionen",
    item_rank_fmt         = "Rang %d",
    item_comment          = "Kommentar",
    item_exclusive        = "Exklusiv",
    item_group            = "Gruppe",
    item_field            = "Feld",
    mandatory_yes         = "Ja",
    mandatory_no          = "Nein",
    mandatory_soft        = "Weich",
    filter_all            = "Alle",
    filter_and            = "UND",
    filter_or             = "ODER",
    filter_answered       = "ist beantwortet",
    filter_empty          = "ist leer",
    filter_in             = "in",
    filter_matches        = "entspricht",
    type_single_choice              = "Einfachauswahl",
    type_single_choice_with_comment = "Einfachauswahl mit Kommentar",
    type_multiple_choice            = "Mehrfachauswahl",
    type_multiple_choice_with_comment = "Mehrfachauswahl mit Kommentar",
    type_text             = "Text",
    type_text_short       = "Text (kurz)",
    type_text_long        = "Text (lang)",
    type_text_other       = "Text (Sonstige)",
    type_number           = "Zahl",
    type_date             = "Datum",
    type_ranking          = "Rangordnung",
    type_file_upload      = "Datei-Upload",
    type_computed         = "Berechnet",
    type_display          = "Anzeige",
    value_multi_y_blank               = "Y = ausgew\u00E4hlt, leer = nicht ausgew\u00E4hlt",
    value_multi_y_blank_with_comment  = "Y = ausgew\u00E4hlt, leer = nicht ausgew\u00E4hlt (plus eine Textvariable `<subq>comment`)",
    value_yes_no                      = "Y = Ja, N = Nein",
    value_gender                      = "M = M\u00E4nnlich, F = Weiblich",
    value_gender_male                 = "M\u00E4nnlich",
    value_gender_female               = "Weiblich",
    value_5point                      = "1, 2, 3, 4, 5 (1 = niedrigster, 5 = h\u00F6chster)",
    value_numeric_input               = "Numerische Eingabe",
    value_array_yes                   = "Ja",
    value_array_uncertain             = "Unsicher",
    value_array_no                    = "Nein",
    value_array_increase              = "Zunahme",
    value_array_same                  = "Keine \u00c4nderung",
    value_array_decrease              = "Abnahme",
    value_order_random                = "Beschriftungen in zuf\u00e4lliger Reihenfolge",
    value_order_alphabetical          = "Beschriftungen in alphabetischer Reihenfolge",
    value_npoint_fmt                  = "%d-Punkt-Skala (1 bis %d)",
    value_free_text_short             = "Freitext (einzeilig)",
    value_free_text                   = "Freitext (mehrzeilig)",
    value_date_input                  = "Datumseingabe",
    value_computed                    = "Berechneter Ausdruck (serverseitig)",
    value_ranking                     = "Rangordnung (Positionen den Teilfragen zugewiesen)",
    value_file_upload                 = "Datei-Upload",
    exclusive_text_fmt    = "Wenn aktiviert, werden alle anderen Auswahlen von %s gel\u00F6scht",
    audit_findings_title  = "Audit-Befunde",
    audit_no_anomalies    = "Keine Anomalien festgestellt.",
    audit_summary_fmt     = "%d Befund(e): %d Fehler, %d Warnung(en), %d Hinweis(e).",
    audit_col_severity    = "Schweregrad",
    audit_col_check       = "Pr\u00FCfung",
    audit_col_location    = "Ort",
    audit_col_language    = "Sprache",
    audit_col_message     = "Meldung",
    audit_severity_error  = "Fehler",
    audit_severity_warning = "Warnung",
    audit_severity_note   = "Hinweis",
    orcid_label           = "ORCID"
  )

  # Spanish and Italian: best-effort translations. Reviewers should
  # validate before using in an official publication.
  es <- list(
    cover_subtitle_review = "Cuestionario",
    cover_subtitle_audit  = "Informe de auditor\u00EDa del cuestionario",
    cover_source_file     = "Archivo de origen",
    cover_survey_id       = "Identificador de la encuesta",
    cover_languages       = "Idiomas",
    cover_groups          = "Grupos",
    cover_questions       = "Preguntas",
    cover_subquestions    = "Subpreguntas",
    cover_answer_options  = "Opciones de respuesta",
    cover_last_modified   = "\u00DAltimo guardado en LimeSurvey",
    cover_generated       = "Generado",
    cover_anonymized        = "Anonimizado",
    cover_save_partial      = "Guardado parcial",
    cover_timestamp         = "Marca de tiempo",
    cover_ip_recorded       = "IP registrada",
    cover_referrer_recorded = "Referente registrado",
    cover_active            = "Activo",
    cover_alias             = "Alias",
    cover_end_url           = "URL final",
    cover_end_url_description = "Descripci\u00F3n de la URL final",
    description_title       = "Descripci\u00F3n",
    toc_title             = "\u00CDndice",
    welcome_text_title    = "Texto de bienvenida",
    end_text_title        = "Texto de cierre",
    variable_index_title  = "\u00CDndice de variables",
    consent_title         = "Protecci\u00F3n de datos y consentimiento",
    quotas_title          = "Cuotas",
    quota_limit           = "L\u00EDmite",
    quota_when_full       = "Al alcanzarse",
    quota_active          = "activa",
    quota_inactive        = "inactiva",
    quota_condition       = "Condici\u00F3n",
    quota_message         = "Mensaje al alcanzarse",
    quota_action_terminate = "terminar la encuesta",
    quota_action_confirm  = "permitir cambiar la respuesta",
    meta_no               = "N.\u00BA",
    meta_variable         = "Variable",
    meta_type             = "Tipo",
    meta_mandatory        = "Obligatorio",
    meta_mandatory_short  = "Oblig.",
    meta_filter           = "Filtro",
    item_language         = "Idioma",
    item_question         = "Pregunta",
    item_subquestion      = "Subpregunta",
    item_help             = "Ayuda",
    item_value            = "Valor",
    item_options          = "Opciones",
    item_value_scale_fmt  = "Valor (escala %d)",
    item_scale            = "Escala",
    item_order            = "Orden",
    item_column           = "Columna",
    item_positions        = "Posiciones",
    item_rank_fmt         = "Puesto %d",
    item_comment          = "Comentario",
    item_exclusive        = "Exclusivo",
    item_group            = "Grupo",
    item_field            = "Campo",
    mandatory_yes         = "S\u00ED",
    mandatory_no          = "No",
    mandatory_soft        = "Suave",
    filter_all            = "Todas",
    filter_and            = "Y",
    filter_or             = "O",
    filter_answered       = "est\u00E1 respondido",
    filter_empty          = "est\u00E1 vac\u00EDo",
    filter_in             = "en",
    filter_matches        = "coincide con",
    type_single_choice              = "Opci\u00F3n \u00FAnica",
    type_single_choice_with_comment = "Opci\u00F3n \u00FAnica con comentario",
    type_multiple_choice            = "Opci\u00F3n m\u00FAltiple",
    type_multiple_choice_with_comment = "Opci\u00F3n m\u00FAltiple con comentario",
    type_text             = "Texto",
    type_text_short       = "Texto (corto)",
    type_text_long        = "Texto (largo)",
    type_text_other       = "Texto (otro)",
    type_number           = "N\u00FAmero",
    type_date             = "Fecha",
    type_ranking          = "Ordenaci\u00F3n",
    type_file_upload      = "Subida de archivo",
    type_computed         = "Calculado",
    type_display          = "Visualizaci\u00F3n",
    value_multi_y_blank               = "Y = seleccionado, vac\u00EDo = no seleccionado",
    value_multi_y_blank_with_comment  = "Y = seleccionado, vac\u00EDo = no seleccionado (m\u00E1s una variable de texto `<subq>comment`)",
    value_yes_no                      = "Y = S\u00ED, N = No",
    value_gender                      = "M = Hombre, F = Mujer",
    value_gender_male                 = "Hombre",
    value_gender_female               = "Mujer",
    value_5point                      = "1, 2, 3, 4, 5 (1 = m\u00E1s bajo, 5 = m\u00E1s alto)",
    value_numeric_input               = "Entrada num\u00E9rica",
    value_array_yes                   = "S\u00ED",
    value_array_uncertain             = "Incierto",
    value_array_no                    = "No",
    value_array_increase              = "Aumentar",
    value_array_same                  = "Sin cambio",
    value_array_decrease              = "Disminuir",
    value_order_random                = "Etiquetas en orden aleatorio",
    value_order_alphabetical          = "Etiquetas en orden alfab\u00e9tico",
    value_npoint_fmt                  = "Escala de %d puntos (1 a %d)",
    value_free_text_short             = "Texto libre (una l\u00EDnea)",
    value_free_text                   = "Texto libre (varias l\u00EDneas)",
    value_date_input                  = "Entrada de fecha",
    value_computed                    = "Expresi\u00F3n calculada (lado servidor)",
    value_ranking                     = "Ordenaci\u00F3n (posiciones asignadas a subpreguntas)",
    value_file_upload                 = "Subida de archivo",
    exclusive_text_fmt    = "Si se marca, borra todas las dem\u00E1s selecciones de %s",
    audit_findings_title  = "Hallazgos de auditor\u00EDa",
    audit_no_anomalies    = "No se detectaron anomal\u00EDas.",
    audit_summary_fmt     = "%d hallazgo(s): %d error(es), %d advertencia(s), %d nota(s).",
    audit_col_severity    = "Gravedad",
    audit_col_check       = "Comprobaci\u00F3n",
    audit_col_location    = "Ubicaci\u00F3n",
    audit_col_language    = "Idioma",
    audit_col_message     = "Mensaje",
    audit_severity_error  = "error",
    audit_severity_warning = "advertencia",
    audit_severity_note   = "nota",
    orcid_label           = "ORCID"
  )

  it <- list(
    cover_subtitle_review = "Questionario",
    cover_subtitle_audit  = "Rapporto di audit del questionario",
    cover_source_file     = "File sorgente",
    cover_survey_id       = "Identificativo dell'indagine",
    cover_languages       = "Lingue",
    cover_groups          = "Gruppi",
    cover_questions       = "Domande",
    cover_subquestions    = "Sotto-domande",
    cover_answer_options  = "Opzioni di risposta",
    cover_last_modified   = "Ultimo salvataggio LimeSurvey",
    cover_generated       = "Generato",
    cover_anonymized        = "Anonimizzato",
    cover_save_partial      = "Salvataggio parziale",
    cover_timestamp         = "Marca temporale",
    cover_ip_recorded       = "IP registrato",
    cover_referrer_recorded = "Referrer registrato",
    cover_active            = "Attivo",
    cover_alias             = "Alias",
    cover_end_url           = "URL finale",
    cover_end_url_description = "Descrizione dell'URL finale",
    description_title       = "Descrizione",
    toc_title             = "Indice",
    welcome_text_title    = "Testo di benvenuto",
    end_text_title        = "Testo di chiusura",
    variable_index_title  = "Indice delle variabili",
    consent_title         = "Protezione dei dati e consenso",
    quotas_title          = "Quote",
    quota_limit           = "Limite",
    quota_when_full       = "Al raggiungimento",
    quota_active          = "attiva",
    quota_inactive        = "inattiva",
    quota_condition       = "Condizione",
    quota_message         = "Messaggio al raggiungimento",
    quota_action_terminate = "terminare il questionario",
    quota_action_confirm  = "consentire la modifica",
    meta_no               = "N.",
    meta_variable         = "Variabile",
    meta_type             = "Tipo",
    meta_mandatory        = "Obbligatoria",
    meta_mandatory_short  = "Obblig.",
    meta_filter           = "Filtro",
    item_language         = "Lingua",
    item_question         = "Domanda",
    item_subquestion      = "Sotto-domanda",
    item_help             = "Aiuto",
    item_value            = "Valore",
    item_options          = "Opzioni",
    item_value_scale_fmt  = "Valore (scala %d)",
    item_scale            = "Scala",
    item_order            = "Ordine",
    item_column           = "Colonna",
    item_positions        = "Posizioni",
    item_rank_fmt         = "Posizione %d",
    item_comment          = "Commento",
    item_exclusive        = "Esclusiva",
    item_group            = "Gruppo",
    item_field            = "Campo",
    mandatory_yes         = "S\u00EC",
    mandatory_no          = "No",
    mandatory_soft        = "Morbido",
    filter_all            = "Tutte",
    filter_and            = "E",
    filter_or             = "O",
    filter_answered       = "\u00E8 compilato",
    filter_empty          = "\u00E8 vuoto",
    filter_in             = "in",
    filter_matches        = "corrisponde a",
    type_single_choice              = "Scelta singola",
    type_single_choice_with_comment = "Scelta singola con commento",
    type_multiple_choice            = "Scelta multipla",
    type_multiple_choice_with_comment = "Scelta multipla con commento",
    type_text             = "Testo",
    type_text_short       = "Testo (breve)",
    type_text_long        = "Testo (lungo)",
    type_text_other       = "Testo (altro)",
    type_number           = "Numero",
    type_date             = "Data",
    type_ranking          = "Classifica",
    type_file_upload      = "Caricamento file",
    type_computed         = "Calcolato",
    type_display          = "Visualizzazione",
    value_multi_y_blank               = "Y = selezionato, vuoto = non selezionato",
    value_multi_y_blank_with_comment  = "Y = selezionato, vuoto = non selezionato (pi\u00F9 una variabile di testo `<subq>comment`)",
    value_yes_no                      = "Y = S\u00EC, N = No",
    value_gender                      = "M = Uomo, F = Donna",
    value_gender_male                 = "Uomo",
    value_gender_female               = "Donna",
    value_5point                      = "1, 2, 3, 4, 5 (1 = pi\u00F9 basso, 5 = pi\u00F9 alto)",
    value_numeric_input               = "Inserimento numerico",
    value_array_yes                   = "S\u00ec",
    value_array_uncertain             = "Incerto",
    value_array_no                    = "No",
    value_array_increase              = "Aumentare",
    value_array_same                  = "Nessun cambiamento",
    value_array_decrease              = "Diminuire",
    value_order_random                = "Etichette in ordine casuale",
    value_order_alphabetical          = "Etichette in ordine alfabetico",
    value_npoint_fmt                  = "Scala a %d punti (1 a %d)",
    value_free_text_short             = "Testo libero (una riga)",
    value_free_text                   = "Testo libero (multi-riga)",
    value_date_input                  = "Inserimento data",
    value_computed                    = "Espressione calcolata (lato server)",
    value_ranking                     = "Classifica (posizioni assegnate alle sotto-domande)",
    value_file_upload                 = "Caricamento file",
    exclusive_text_fmt    = "Se selezionata, cancella tutte le altre selezioni di %s",
    audit_findings_title  = "Risultati dell'audit",
    audit_no_anomalies    = "Nessuna anomalia rilevata.",
    audit_summary_fmt     = "%d risultato(i): %d errore(i), %d avvertimento(i), %d nota(e).",
    audit_col_severity    = "Gravit\u00E0",
    audit_col_check       = "Controllo",
    audit_col_location    = "Posizione",
    audit_col_language    = "Lingua",
    audit_col_message     = "Messaggio",
    audit_severity_error  = "errore",
    audit_severity_warning = "avvertimento",
    audit_severity_note   = "nota",
    orcid_label           = "ORCID"
  )

  pack <- switch(
    lang,
    "en" = base, "fr" = fr, "de" = de, "es" = es, "it" = it,
    base
  )
  pack
}

#' Localized methodological type label for a question
#'
#' Maps the question's LimeSurvey type code (and optional theme name
#' fallback) to the appropriate `theme$chrome$type_*` string. The
#' methodological collapse is the same as [lss_methodological_label()]
#' (List/Array/Y/G/5 -> Single choice, M/P -> Multiple choice, ...);
#' the localized string replaces the English one at the call site so
#' the meta-table reads in the chrome language.
#'
#' @keywords internal
#' @noRd
lss_localized_type_label <- function(q, theme) {
  chrome <- theme$chrome
  # Naming `EXPR =` explicitly avoids the R CMD check note that
  # `switch()` triggers when one of the case labels ("E") would
  # partial-match the formal parameter `EXPR`.
  key <- switch(
    EXPR = as.character(q$type),
    "L" = "type_single_choice", "!" = "type_single_choice",
    "Y" = "type_single_choice", "G" = "type_single_choice",
    "5" = "type_single_choice", "F" = "type_single_choice",
    "1" = "type_single_choice", "A" = "type_single_choice",
    "B" = "type_single_choice", "C" = "type_single_choice",
    "E" = "type_single_choice", "H" = "type_single_choice",
    ":" = "type_single_choice",
    "O" = "type_single_choice_with_comment",
    "M" = "type_multiple_choice",
    "P" = "type_multiple_choice_with_comment",
    "S" = "type_text_short",
    # T (long free text) and U (huge free text) differ only in textarea
    # size -- both store multi-line free text -- so they collapse to the
    # same "Text (long)" label, the same way List (radio) / List
    # (dropdown) collapse to "Single choice". S (short free text) stays
    # distinct because it is single-line (no line breaks in the data).
    "T" = "type_text_long",
    "U" = "type_text_long",
    "Q" = "type_text",
    ";" = "type_text",
    "N" = "type_number",
    "K" = "type_number",
    "D" = "type_date",
    "R" = "type_ranking",
    "|" = "type_file_upload",
    "*" = "type_computed",
    "X" = "type_display",
    "I" = "type_display",
    NA_character_
  )
  if (!is.na(key)) return(chrome[[key]])
  # Fall back to the type label baked at model-build time (English
  # methodological label) so unknown plugin types still appear with
  # their best-effort name.
  q$type_label
}

#' Resolve and validate the `chrome_lang` argument
#'
#' Returns one of `"en"`, `"fr"`, `"de"`, `"es"`, `"it"`. When `NULL`,
#' falls back to the first content language if it is supported,
#' otherwise to English. Unknown explicit values are rejected with a
#' classed condition so callers can catch them programmatically.
#'
#' @keywords internal
#' @noRd
lss_resolve_chrome_lang <- function(chrome_lang, content_languages) {
  supported <- c("en", "fr", "de", "es", "it")
  if (is.null(chrome_lang)) {
    primary <- content_languages[1L]
    if (!is.na(primary) && primary %in% supported) return(primary)
    return("en")
  }
  if (!is.character(chrome_lang) || length(chrome_lang) != 1L ||
      is.na(chrome_lang)) {
    lssdoc_abort(
      c(
        "{.arg chrome_lang} must be {.code NULL} or one of {.val {supported}}.",
        "i" = "Got {.val {chrome_lang}}."
      ),
      class = "lssdoc_bad_chrome_lang"
    )
  }
  if (!chrome_lang %in% supported) {
    lssdoc_abort(
      c(
        "{.arg chrome_lang} {.val {chrome_lang}} is not supported.",
        "i" = "Supported values: {.val {supported}}."
      ),
      class = "lssdoc_bad_chrome_lang"
    )
  }
  chrome_lang
}
